### ISSUE TITLE
A few suggestions if they are possible

### ISSUE THREAD

**Issue by SmartKirb99** [protogenposting/Marrow#29] opened 2024-10-28 22:46 UTC
If it is possible I would like to suggest figuring out how to make the exe file in MarrowRunner to make it so that people who do not have Intellij and JDK version 21 are able to run Marrow, I would also like to suggest a launcher of sorts, similar to that of Minecraft Java Edition's (In the sense of like, update news and possibly being able to access old versions of Marrow. If need be, I could potentially make a fork of the project and try to add said features to the your project.

**Comment by protogenposting** [comment] 2024-10-28 22:52
duplicate of #28

**Comment by SmartKirb99** [comment] 2024-10-28 23:10
I mean, technically this counts as 2 suggestions, only one of them was a duplicate, at least I believe, being the launcher, the other one was figuring out how to make the MarrowRunner executable file run without the JDK of 11

**Comment by protogenposting** [comment] 2024-10-28 23:12
those are both solved by the launcher, so I feel like it is a single issue

also in all future issues please seperate your suggestions into seperate issues so they can be tracked and marked as completed properly

**Closed by protogenposting** 2024-10-28 23:12 UTC
Labels: duplicate
